### ISSUE TITLE
First travis test results 

### ISSUE THREAD

**Issue by posix4e** [highperformancecoder/ecolab#2]
https://travis-ci.org/posix4e/ecolab/builds/103014855
- A couple of things. Looks like i need to install:

6) UNURAN
12) MPI 1.x
13) ParMetis

Also i noticed you are trying to xwindows work. Is there a useful set of console tests we can run automagically. Also the tests obviously didn't succeed but the make sure did return as if the tests pass. Should we change this?

**Comment by highperformancecoder** [comment]
On Sun, Jan 17, 2016 at 04:41:56PM -0800, Alex Newman wrote:

> https://travis-ci.org/posix4e/ecolab/builds/103014855
> - A couple of things. Looks like i need to install:
> 
> 6) UNURAN
> 12) MPI 1.x
> 13) ParMetis
> 
> Also i noticed you are trying to xwindows work. Is there a useful set of console tests we can run automagically. Also the tests obviously didn't succeed but the make sure did return as if the tests pass. Should we change this?

Are you sure the tests didn't succeed? If so, then yes, that is a
bug. Make sure should return a non-zero code if the tests fail. I may
not have noticed if this wasn't working, because I usually run the
tests from the Aegis test harness, not the make sure target.

The GUI tests should be able to be run with an Xvfb X server in the
background. You might need to install it in a relevant package in
.travis.yml.

Feel free to propose changes to the test scripts to get them to run on Travis.

Cheers

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/ecolab/issues/2

## 

---

Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au

## Economics, Kingston University         http://www.hpcoders.com.au

**Comment by highperformancecoder** [comment]
Travis is fine now.
